---
version: "3.4"

services:
  app:
    image: ghcr.io/hargata/lubelogger:latest
    build: .
    restart: unless-stopped
    # volumes used to keep data persistent
    volumes:
      - /media/bulk/portainer/volumes/lube-logger_config:/App/config
      - /media/bulk/portainer/volumes/lube-logger_data:/App/data
      - /media/bulk/portainer/volumes/lube-logger_translations:/App/wwwroot/translations
      - /media/bulk/portainer/volumes/lube-logger_documents:/App/wwwroot/documents
      - /media/bulk/portainer/volumes/lube-logger_images:/App/wwwroot/images
      - /media/bulk/portainer/volumes/lube-logger_temp:/App/wwwroot/temp
      - /media/bulk/portainer/volumes/lube-logger_log:/App/log
      - /media/bulk/portainer/volumes/lube-logger_keys:/root/.aspnet/DataProtection-Keys
    # expose port and/or use serving via traefik
    ports:
      - 8080:8080
    env_file:
      - .env

volumes:
  config:
  data:
  translations:
  documents:
  images:
  temp:
  log:
  keys:
